version: '3'
services:
  db:
    image: postgres:11-alpine
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=demo
    ports:
      - '5432:5432'
  backend:
    image: backend
    container_name: backend
    environment:
      SPRING_JPA_HIBERNATE_DDL-AUTO: create
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD:
    ports:
      - '8999:8999'
    links:
      - db
  frontend:
    image: frontend
    container_name: frontend
    ports:
      - '8080:8080'
    links:
      - backend